### ISSUE TITLE
unable to run KAF2D.

### ISSUE THREAD

**Issue by shruti-jadon** [ispamm/kernel-activation-functions#1]
Its running perfectly for KAF, but KAF2D is throwing following error.

tmp = -torch.mul((torch.add(X[:, 0:self.num_parameters].unsqueeze(4), - Variable(self.Dx).view(1, 1, 1, 1, -1))) ** 2, self.gamma) - \
RuntimeError: Expected object of type Variable[torch.FloatTensor] but found type Variable[torch.DoubleTensor] for argument #1 'other'

**Comment by ispamm** [comment]
Are you simply running the demo from the repository? Can you tell me your PyTorch version?

You can force either X or self.Dx to be of float type as follows:

`X.data = X.data.float()`
